agent/__init__.py

Any other exceptions? May be suppress them with `noqa` pragma?

Fix linter error.

---

tests/conftest.py
tests/test_agent.py

Make linter happy.

---

.circleci/config.yml

Add CI test runner.

---

agent/security_helper.py
requirements.txt
tests/test_agent.py

`pytest agent/security_helper.py`

Add is_firewall_enabled() check.

---

.circleci/config.yml

Install iptables in CI.

---

agent/__init__.py

Add claim by link.

---

.circleci/config.yml
agent/journal_helper.py
requirements.txt
tests/test_agent.py

Read the system journal, count the number of failed attempts logged by sshd.
Closes #13

Count the number of ssh logins by reading system journal.

---

debian/changelog
debian/postinst
debian/wott-agent.service
debian/wott-agent.timer

Fix postinst script.

---

agent/__init__.py
agent/__main__.py
setup.py

Add commandline argument.

---

debian/changelog
debian/postinst

Meaningful message from postinst.

---

agent/__main__.py

Nicely formatted cmdline help.

---

agent/__init__.py
debian/changelog
tests/conftest.py
tests/test_agent.py

Send open ports in ping request.

---

agent/__init__.py

Fixes #40.
Requires WoTTsecurity/api#105.

New claim_device URL in Dash.

---

agent/__init__.py
agent/security_helper.py
tests/test_agent.py

Relates to WoTTsecurity/api#107

Send Firewall state

---

agent/security_helper.py
debian/changelog

Don't send processes environment vars

---

agent/__init__.py
debian/changelog

Don't send processes as the server is not ready for that yet.

---

agent/__init__.py
tests/test_agent.py

Receive, store and use fallback renewal token.

---

agent/__init__.py
agent/security_helper.py
debian/changelog
requirements.txt
tests/test_agent.py

Block ports and networks received in ping response.
Contains #64 (merge it first)

Control iptables

---

agent/__init__.py
debian/changelog

Send processes, scan_info, netstat as nested objects.

---

.circleci/config.yml
agent/__init__.py
agent/iptc_helper.py
agent/security_helper.py
debian/changelog
debian/control
requirements-dev.txt
requirements.txt
tests/test_agent.py

Revert the python-iptables dependency back to Stretch version (0.11.0)

Add iptc.easy from python-iptables

---

.circleci/config.yml
tests/conftest.py
tests/test_agent.py

Relates to WoTTSecurity/api#69
Also fix package upload to PackageCloud.

Add tests for networks and port blocking routines

---

agent/__init__.py
agent/security_helper.py

Update agent side in order to support ports blocking data format change in https://github.com/WoTTsecurity/api/issues/69

UDP ports blocking fix

---

agent/__init__.py

Send selinux status in ping message.

---

agent/security_helper.py

Block ports together with hosts.

---

agent/__init__.py
tests/test_agent.py

Send login attempts stats.

---

agent/security_helper.py
debian/changelog
tests/test_agent.py

Don't use iptc.easy for deleting rules.

---

agent/__init__.py
debian/changelog

Send ping after bootstrap.

---

agent/security_helper.py
debian/changelog

Don't filter out port block rules and WOTT_LOG_DROP

---

agent/security_helper.py
debian/changelog
tests/conftest.py
tests/test_agent.py

Allow blocking ipv6 ports and networks.

---

agent/security_helper.py
tests/conftest.py

Send ip_version for open ports.

---

agent/security_helper.py

This is a workaround for two bugs in iptc:
1. Can't create two `iptc.Chain`s of ipv4 and ipv6 tables with the same name, and
1. `iptc.easy` can't have two tables in batch mode because of `_BATCH_MODE` global variable.

Fix for piling up of ipv4 rules

---

agent/__init__.py
agent/__main__.py
tests/test_agent.py

#90 Add grouping by name to fetch_credentials()

---

agent/security_helper.py
debian/changelog
tests/conftest.py
tests/test_agent.py

 Treat 0.0.0.0 and ::: as "any address"

---

agent/__init__.py
tests/test_agent.py

closes #172, (agent side)
[api side PR](https://github.com/WoTTsecurity/api/pull/241)

172 wipe claim tocken if claimed

---

agent/security_helper.py
tests/test_agent.py

A companion agent-side task for https://github.com/WoTTsecurity/api/issues/227

Fix definition of 'Firewall Enabled'

---

agent/__init__.py
tests/cassettes/test_send_ping.yaml

Closes #114
Requires wottsecurity/api#246

Apply iptables changes before gathering and sending them.

---

agent/__main__.py
debian/postinst

closes #94 
I don't sure about the text in case if claimed.

Don't display post-installation instruction if claimed

---

agent/iptc_helper.py
agent/security_helper.py

 Send NAT and MANGLE tables, v4 and v6.

---

debian/postinst

change == to = in if[  ]

---

.circleci/config.yml
agent/__init__.py
agent/__main__.py
agent/executor.py
tests/test_agent.py

Interprocess Locker

---

debian/control

Add dependency on rng-tools.

---

README.md

Main WoTT Agent README has been updated with a brief summary of the Google Core IoT and Simple WebApp examples with appropriate links to each webpage.

WoTT Agent README.md updated with links to new Google Core IoT and Simple WebApp docs

---

docs/examples/simple-webapp-auth/README.md

- Fixed image links so they actually show
- Run test of commands works
- Tweaked document to make it more visually appealing

RE #127: Fixing Basic HTTP Auth Simple WebApp example with image links

---

agent/__init__.py

Write device id to metadata file.

---

README.md
agent/__init__.py
docs/examples/simple-webapp-auth/README.md
docs/examples/simple-webapp-auth/app.py

- Fixing repository issues
- Updated with relevant changes

Simple WebApp Basic HTTP Auth example: Fixing merge conflicts with my original repo

---

agent/__init__.py
agent/rpi_helper.py

Installation and confinement detection

---

agent/__init__.py
tests/test_agent.py

permissions for credentials

---

README.md

- Introduced sections discussing credentials vs certificates and why we need both
- Beginning to split up examples into credentials vs certificates
- General updating and writing changes to be more consistent with the rest of docs

Updating main README.md to be more polished and informative

---

agent/__init__.py
agent/iptables_helper.py
agent/iptc_helper.py
agent/security_helper.py
tests/conftest.py
tests/test_agent.py

Closes #139.
Closes #151 
Handle iptables errors (log them).
Implement "block by default policy" logic.
Remove "firewall_enabled".
Move iptables stuff into new module iptables_helper.

Switchable iptables policy + iptables errors handling.

---

agent/__init__.py
tests/test_agent.py

change owner to linux_user in credentials

---

agent/__init__.py

minor code improvement (in fetch credentials() )

---

README.md

- added index with brief summary linking to screenly use case

Updating main 'README.md' to include link to 'Screenly' use case

---

agent/__init__.py

fix credentials permissions

---

agent/__init__.py
tests/test_agent.py

refactor mtls requests

---

agent/__init__.py
agent/__main__.py
tests/test_agent.py

closes  https://github.com/WoTTsecurity/api/issues/273
(agent side)

add device-specific metadata fetching

---

README.md
docs/examples/adafruit-io/README.md

- Fixed capitalisation in adafruit example 
- Fixed additional line in README.md

Formatting

---

README.md

Updating main README to link to new blog posts

---

agent/__init__.py
tests/test_agent.py

closes https://github.com/WoTTsecurity/api/issues/303
agent side

303 modify credentials to support multiple key values

---

agent/__init__.py
tests/test_agent.py

closes: https://github.com/WoTTsecurity/api/issues/304
api side PR here: https://github.com/WoTTsecurity/api/pull/316

automatically claim device by enrollment token in config

---

agent/__main__.py

Add manual credentials fetching option

---

tests/test_agent.py

Increase executor interval to fix flaky test_independent_lockers.

---

.circleci/config.yml
debian/control
debian/install
debian/rules
debian/usercustomize.py

Build only on Stretch. Push to Buster, Stretch and Xenial.

---

.circleci/config.yml
debian/control
debian/install
debian/rules
debian/usercustomize.py

Reverts WoTTsecurity/agent#203

Revert "Build only on Stretch. Push to Buster, Stretch and Xenial."

---

agent/__init__.py
agent/__main__.py

closes [api #351](https://github.com/WoTTsecurity/api/issues/351)
also 
add  back `--debug` command line key

change api endpoint names

---

agent/__init__.py
agent/security_helper.py
tests/conftest.py
tests/test_agent.py

Audit config files

---

agent/__init__.py
agent/security_helper.py
tests/conftest.py
tests/test_agent.py

Reverts WoTTsecurity/agent#214

Revert "Audit config files"

---

snap/snapcraft.yaml

In place of accidentally merged #228 .
Addition: Correct bin/ path of tools in snap.

Integrate with agent-snap 

---

agent/__init__.py
agent/security_helper.py
tests/conftest.py
tests/test_agent.py

*in place of accidentally merged #214*

Audit config files.

---

agent/__init__.py
agent/rpi_helper.py

Read and parse /etc/os-release.

---

agent/__init__.py
agent/rpi_helper.py

Check for auto upgrades

---

agent/security_helper.py

Check each process if it's running in Docker.

---

agent/__init__.py
agent/security_helper.py

Check for mysql root access.

---

debian/install
debian/wott-agent-self-update.service
debian/wott-agent-self-update.sh
debian/wott-agent-self-update.timer

Self-update systemd timer.

---

agent/security_helper.py

Don't use lscpu -J option, not available on older systems.

---

agent/security_helper.py
tests/conftest.py
tests/test_agent.py

Send list of usernames which use default passwords.

---

agent/security_helper.py

https://github.com/WoTTsecurity/agent/issues/257#issuecomment-587013063

Ask before replacing PasswordAuthentication.

---

bin/install.sh

* Fixes detection of RedHat derived installations
* Enables Amazon Linux 2
* Fixes indentation

Adds installation method for Amazon Linux 2

---

.circleci/config.yml
bin/wott-agent-install.sh
bin/wott-agent-remove.sh
bin/wott-agent-upgrade.sh
bin/wott-agent.sh
debian/wott-agent-self-update.sh
debian/wott-agent.service

Fixes auto-update and the daemon service.
Both services get restarted and continue to work after package upgrade.

Fix systemd scripts in Amazon.

---

agent/os_helper.py

Instead of currently running one used before.
This is gonna solve the recently found error with missing kernel package and also fix an inconsistency in `device_registry.models.Device.cpu_vulnerable`.

Send kernel package info for the newest kernel package

---

.circleci/config.yml
agent/__init__.py
agent/os_helper.py

Fixes #261 
Also adds a lock around `/opt/wott` directory creation.
Fixes #275

Fix auto-upgrade detection for Debian.

---

agent/__init__.py
agent/__main__.py
agent/os_helper.py
agent/security_helper.py

New command: `wott-agent upgrade pkg [pkg...]`
#257

Package upgrade command

---

agent/__main__.py

Don't print out the version every time.

---

agent/__main__.py

Remove unused __version__ in __main__.

---

agent/os_helper.py

Forbid yum to use color in its output.
